# Generated by Django 5.0 on 2023-12-13 09:35

import czat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=250, verbose_name='treść wiadomości')),
                ('data_pub', models.DateTimeField(auto_now_add=True, verbose_name='data publikacji')),
                ('autor', models.ForeignKey(on_delete=czat.models.delete, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
